/*
 * Copyright 2016 Tom Thorpe
 *
 * Distributed under the ISC Licence 
 *
 * Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * Author: Tom Thorpe
 */

 module.exports = {

  models : {
    "MN8X2B/A": "UK iPhone 7 32GB Black",
    "MN8Y2B/A": "UK iPhone 7 32GB Silver",
    "MN902B/A": "UK iPhone 7 32GB Gold",
    "MN912B/A": "UK iPhone 7 32GB Rose Gold",
    "MN922B/A": "UK iPhone 7 128GB Black",
    "MN932B/A": "UK iPhone 7 128GB Silver",
    "MN942B/A": "UK iPhone 7 128GB Gold",
    "MN952B/A": "UK iPhone 7 128GB Rose Gold",
    "MN962B/A": "UK iPhone 7 128GB Jet Black",
    "MN972B/A": "UK iPhone 7 256GB Black",
    "MN982B/A": "UK iPhone 7 256GB Silver",
    "MN992B/A": "UK iPhone 7 256GB Gold",
    "MN9A2B/A": "UK iPhone 7 256GB Rose Gold",
    "MN9C2B/A": "UK iPhone 7 256GB Jet Black",
    "MN4M2B/A": "UK iPhone 7 Plus 128GB Black",
    "MN4P2B/A": "UK iPhone 7 Plus 128GB Silver",
    "MN4Q2B/A": "UK iPhone 7 Plus 128GB Gold",
    "MN4U2B/A": "UK iPhone 7 Plus 128GB Rose Gold",
    "MN4V2B/A": "UK iPhone 7 Plus 128GB Jet Black",
    "MN4W2B/A": "UK iPhone 7 Plus 256GB Black",
    "MN4X2B/A": "UK iPhone 7 Plus 256GB Silver",
    "MN4Y2B/A": "UK iPhone 7 Plus 256GB Gold",
    "MN502B/A": "UK iPhone 7 Plus 256GB Rose Gold",
    "MN512B/A": "UK iPhone 7 Plus 256GB Jet Black",
    "MNQM2B/A": "UK iPhone 7 Plus 32GB Black",
    "MNQN2B/A": "UK iPhone 7 Plus 32GB Silver",
    "MNQP2B/A": "UK iPhone 7 Plus 32GB Gold",
    "MNQQ2B/A": "UK iPhone 7 Plus 32GB Rose Gold",

    "MN9D2LL/A" : "US iPhone 7 32GB Black (AT&T GSM)",
    "MN9E2LL/A" : "US iPhone 7 32GB Silver (AT&T GSM)",
    "MN9F2LL/A" : "US iPhone 7 32GB Gold (AT&T GSM)",
    "MN9G2LL/A" : "US iPhone 7 32GB Rose Gold (AT&T GSM)",
    "MN9H2LL/A" : "US iPhone 7 128GB Black (AT&T GSM)",
    "MN9J2LL/A" : "US iPhone 7 128GB Silver (AT&T GSM)",
    "MN9K2LL/A" : "US iPhone 7 128GB Gold (AT&T GSM)",
    "MN9L2LL/A" : "US iPhone 7 128GB Rose Gold (AT&T GSM)",
    "MN9M2LL/A" : "US iPhone 7 128GB Jet Black (AT&T GSM)",
    "MN9N2LL/A" : "US iPhone 7 256GB Black (AT&T GSM)",
    "MN9P2LL/A" : "US iPhone 7 256GB Silver (AT&T GSM)",
    "MN9Q2LL/A" : "US iPhone 7 256GB Gold (AT&T GSM)",
    "MN9R2LL/A" : "US iPhone 7 256GB Rose Gold (AT&T GSM)",
    "MN9T2LL/A" : "US iPhone 7 256GB Jet Black (AT&T GSM)",
    "MN9U2LL/A" : "US iPhone 7 32GB Black (T-Mobile GSM)",
    "MN9V2LL/A" : "US iPhone 7 32GB Silver (T-Mobile GSM)",
    "MN9W2LL/A" : "US iPhone 7 32GB Gold (T-Mobile GSM)",
    "MN9X2LL/A" : "US iPhone 7 32GB Rose Gold (T-Mobile GSM)",
    "MN9Y2LL/A" : "US iPhone 7 128GB Black (T-Mobile GSM)",
    "MNA02LL/A" : "US iPhone 7 128GB Silver (T-Mobile GSM)",
    "MNA32LL/A" : "US iPhone 7 128GB Gold (T-Mobile GSM)",
    "MNA42LL/A" : "US iPhone 7 128GB Rose Gold (T-Mobile GSM)",
    "MNA52LL/A" : "US iPhone 7 128GB Jet Black (T-Mobile GSM)",
    "MNA62LL/A" : "US iPhone 7 256GB Black (T-Mobile GSM)",
    "MNA72LL/A" : "US iPhone 7 256GB Silver (T-Mobile GSM)",
    "MNA82LL/A" : "US iPhone 7 256GB Gold (T-Mobile GSM)",
    "MNA92LL/A" : "US iPhone 7 256GB Rose Gold (T-Mobile GSM)",
    "MNAA2LL/A" : "US iPhone 7 256GB Jet Black (T-Mobile GSM)",
    "MNAC2LL/A" : "US iPhone 7 32GB Black (Verizon)",
    "MNAD2LL/A" : "US iPhone 7 32GB Silver (Verizon)",
    "MNAE2LL/A" : "US iPhone 7 32GB Gold (Verizon)",
    "MNAF2LL/A" : "US iPhone 7 32GB Rose Gold (Verizon)",
    "MNAJ2LL/A" : "US iPhone 7 128GB Black (Verizon)",
    "MNAK2LL/A" : "US iPhone 7 128GB Silver (Verizon)",
    "MNAL2LL/A" : "US iPhone 7 128GB Gold (Verizon)",
    "MNAM2LL/A" : "US iPhone 7 128GB Rose Gold (Verizon)",
    "MNAP2LL/A" : "US iPhone 7 128GB Jet Black (Verizon)",
    "MNAQ2LL/A" : "US iPhone 7 256GB Black (Verizon)",
    "MNAU2LL/A" : "US iPhone 7 256GB Silver (Verizon)",
    "MNAV2LL/A" : "US iPhone 7 256GB Gold (Verizon)",
    "MNAW2LL/A" : "US iPhone 7 256GB Rose Gold (Verizon)",
    "MNAX2LL/A" : "US iPhone 7 256GB Jet Black (Verizon)",
    "MNAY2LL/A" : "US iPhone 7 32GB Black (Sprint)",
    "MNC02LL/A" : "US iPhone 7 32GB Silver (Sprint)",
    "MNC12LL/A" : "US iPhone 7 32GB Gold (Sprint)",
    "MNC22LL/A" : "US iPhone 7 32GB Rose Gold (Sprint)",
    "MNC32LL/A" : "US iPhone 7 128GB Black (Sprint)",
    "MNC42LL/A" : "US iPhone 7 128GB Silver (Sprint)",
    "MNC52LL/A" : "US iPhone 7 128GB Gold (Sprint)",
    "MNC62LL/A" : "US iPhone 7 128GB Rose Gold (Sprint)",
    "MNC72LL/A" : "US iPhone 7 128GB Jet Black (Sprint)",
    "MNC82LL/A" : "US iPhone 7 256GB Black (Sprint)",
    "MNC92LL/A" : "US iPhone 7 256GB Silver (Sprint)",
    "MNCA2LL/A" : "US iPhone 7 256GB Gold (Sprint)",
    "MNCC2LL/A" : "US iPhone 7 256GB Rose Gold (Sprint)",
    "MNCD2LL/A" : "US iPhone 7 256GB Jet Black (Sprint)",
    "MN522LL/A" : "US iPhone 7 Plus 128GB Black (GSM AT&T)",
    "MN532LL/A" : "US iPhone 7 Plus 128GB Silver (GSM AT&T)",
    "MN552LL/A" : "US iPhone 7 Plus 128GB Gold (GSM AT&T)",
    "MN562LL/A" : "US iPhone 7 Plus 128GB Rose Gold (GSM AT&T)",
    "MN572LL/A" : "US iPhone 7 Plus 128GB Jet Black (GSM AT&T)",
    "MN592LL/A" : "US iPhone 7 Plus 256GB Black (GSM AT&T)",
    "MN5C2LL/A" : "US iPhone 7 Plus 256GB Silver (GSM AT&T)",
    "MN5D2LL/A" : "US iPhone 7 Plus 256GB Gold (GSM AT&T)",
    "MN5E2LL/A" : "US iPhone 7 Plus 256GB Rose Gold (GSM AT&T)",
    "MN5F2LL/A" : "US iPhone 7 Plus 256GB Jet Black (GSM AT&T)",
    "MN5G2LL/A" : "US iPhone 7 Plus 128GB Black (GSM T-Mobile)",
    "MN5H2LL/A" : "US iPhone 7 Plus 128GB Silver (GSM T-Mobile)",
    "MN5J2LL/A" : "US iPhone 7 Plus 128GB Gold (GSM T-Mobile)",
    "MN5K2LL/A" : "US iPhone 7 Plus 128GB Rose Gold (GSM T-Mobile)",
    "MN5L2LL/A" : "US iPhone 7 Plus 128GB Jet Black (GSM T-Mobile)",
    "MN5M2LL/A" : "US iPhone 7 Plus 256GB Black (GSM T-Mobile)",
    "MN5N2LL/A" : "US iPhone 7 Plus 256GB Silver (GSM T-Mobile)",
    "MN5P2LL/A" : "US iPhone 7 Plus 256GB Gold (GSM T-Mobile)",
    "MN5Q2LL/A" : "US iPhone 7 Plus 256GB Rose Gold (GSM T-Mobile)",
    "MN5R2LL/A" : "US iPhone 7 Plus 256GB Jet Black (GSM T-Mobile)",
    "MN5T2LL/A" : "US iPhone 7 Plus 128GB Black (Verizon)",
    "MN5U2LL/A" : "US iPhone 7 Plus 128GB Silver (Verizon)",
    "MN5V2LL/A" : "US iPhone 7 Plus 128GB Gold (Verizon)",
    "MN5W2LL/A" : "US iPhone 7 Plus 128GB Rose Gold (Verizon)",
    "MN5X2LL/A" : "US iPhone 7 Plus 128GB Jet Black (Verizon)",
    "MN5Y2LL/A" : "US iPhone 7 Plus 256GB Black (Verizon)",
    "MN602LL/A" : "US iPhone 7 Plus 256GB Silver (Verizon)",
    "MN612LL/A" : "US iPhone 7 Plus 256GB Gold (Verizon)",
    "MN622LL/A" : "US iPhone 7 Plus 256GB Rose Gold (Verizon)",
    "MN632LL/A" : "US iPhone 7 Plus 256GB Jet Black (Verizon)",
    "MN642LL/A" : "US iPhone 7 Plus 128GB Black (Sprint)",
    "MN652LL/A" : "US iPhone 7 Plus 128GB Silver (Sprint)",
    "MN662LL/A" : "US iPhone 7 Plus 128GB Gold (Sprint)",
    "MN672LL/A" : "US iPhone 7 Plus 128GB Rose Gold (Sprint)",
    "MN682LL/A" : "US iPhone 7 Plus 128GB Jet Black (Sprint)",
    "MN692LL/A" : "US iPhone 7 Plus 256GB Black (Sprint)",
    "MN6A2LL/A" : "US iPhone 7 Plus 256GB Silver (Sprint)",
    "MN6C2LL/A" : "US iPhone 7 Plus 256GB Gold (Sprint)",
    "MN6D2LL/A" : "US iPhone 7 Plus 256GB Rose Gold (Sprint)",
    "MN6E2LL/A" : "US iPhone 7 Plus 256GB Jet Black (Sprint)",
    "MNQR2LL/A" : "US iPhone 7 Plus 32GB Black (GSM AT&T)",
    "MNQT2LL/A" : "US iPhone 7 Plus 32GB Silver (GSM AT&T)",
    "MNQU2LL/A" : "US iPhone 7 Plus 32GB Gold (GSM AT&T)",
    "MNQV2LL/A" : "US iPhone 7 Plus 32GB Rose Gold (GSM AT&T)"
}

}
